steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mt5-websocket-client', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mt5-websocket-client']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'mt5-websocket-client',
           '--image', 'gcr.io/$PROJECT_ID/mt5-websocket-client',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--set-env-vars', 'MT5_SERVER_URL=$_MT5_SERVER_URL,FOREX_SYMBOLS=$_FOREX_SYMBOLS,STORAGE_TYPE=$_STORAGE_TYPE,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME',
           '--min-instances', '1',
           '--max-instances', '1',
           '--timeout', '3600s',
           '--concurrency', '1',
           '--cpu', '1',
           '--memory', '512Mi']

substitutions:
  _MT5_SERVER_URL: ${_MT5_SERVER_URL}
  _FOREX_SYMBOLS: ${_FOREX_SYMBOLS}
  _STORAGE_TYPE: ${_STORAGE_TYPE}
  _GCS_BUCKET_NAME: ${_GCS_BUCKET_NAME}