name: Deploy MT5 to BigQuery Cloud Function

on:
  push:
    branches:
      - main
    paths:
      - 'functions/mt5 to cloudfunction/**'
      - 'terraform/**'
      - '.github/workflows/google-cloudrun-docker.yml'
  workflow_dispatch:  # Allows manual triggering

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy-infrastructure:
    name: Deploy Cloud Function with Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Needed for Google auth

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          
      - name: Create tmp directory for archives
        run: mkdir -p terraform/tmp
          
      - name: Zip Cloud Function source
        run: |
          cd functions/mt5\ to\ cloudfunction
          zip -r ../../terraform/tmp/mt5_to_cloudfunction.zip .
          
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -var="project_id=$PROJECT_ID" -var="region=$REGION" -out=tfplan
          
      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve tfplan
          
      - name: Show Function URL
        working-directory: ./terraform
        run: |
          echo "MT5 to BigQuery function URL:"
          terraform output mt5_function_url
          echo ""
          echo "Deployment complete! Use the function URL above to connect your MT5 client."